name: flutter_newsapp
description: A Flutter News App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  floor: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.0.0
  get_it: ^7.2.0
  google_fonts: ^2.2.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  retrofit: ^3.0.1
  shimmer: ^2.0.0
  webview_flutter: ^3.0.0
  transparent_image: ^2.0.0
  hive_flutter: ^1.1.0
  

dev_dependencies:
  build_runner: ^2.1.7
  floor_generator: ^1.2.0
  hive_generator: ^1.1.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.4
  retrofit_generator: ^3.0.1

flutter:
  uses-material-design: true
  
